//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
//<auto-generated>
//  This code was generated by a tool
//  Runtime Version: 4.0.30319.42000
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//</auto-generated>
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
using System;
using System.CodeDom.Compiler;
using WhatsOnTheFridge.Core.Test.Builders.General;

namespace WhatsOnTheFridge.Core.Test.Builders
{

    [GeneratedCode("Builders", "1.0")]
    public partial class DomainEntityBuilder : Builder<WhatsOnThe.Model.DomainEntity>
    {

        [GeneratedCode("ModelBuilders", "1.0")]
        public override WhatsOnThe.Model.DomainEntity Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<WhatsOnThe.Model.DomainEntity>(new WhatsOnThe.Model.DomainEntity
                {
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public static DomainEntityBuilder Default()
        {
            return new DomainEntityBuilder();
        }


    }

    [GeneratedCode("Builders", "1.0")]
    public partial class ItemBuilder : Builder<WhatsOnThe.Model.Item>
    {
        private Lazy<System.DateTime> _addedDate = new Lazy<System.DateTime>(default(System.DateTime));
        private Lazy<System.String> _description = new Lazy<System.String>(default(System.String));
        private Lazy<System.Nullable<System.DateTime>> _expirationDate = new Lazy<System.Nullable<System.DateTime>>(default(System.Nullable<System.DateTime>));
        private Lazy<System.Int32> _id = new Lazy<System.Int32>(default(System.Int32));
        private Lazy<WhatsOnThe.Model.Location> _location = new Lazy<WhatsOnThe.Model.Location>(default(WhatsOnThe.Model.Location));
        private Lazy<System.Nullable<System.Int32>> _locationId = new Lazy<System.Nullable<System.Int32>>(default(System.Nullable<System.Int32>));
        private Lazy<System.String> _name = new Lazy<System.String>(default(System.String));
        private Lazy<System.Int32> _quantity = new Lazy<System.Int32>(default(System.Int32));

        [GeneratedCode("ModelBuilders", "1.0")]
        public override WhatsOnThe.Model.Item Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<WhatsOnThe.Model.Item>(new WhatsOnThe.Model.Item
                {
                    AddedDate = _addedDate.Value,
                    Description = _description.Value,
                    ExpirationDate = _expirationDate.Value,
                    Id = _id.Value,
                    Location = _location.Value,
                    LocationId = _locationId.Value,
                    Name = _name.Value,
                    Quantity = _quantity.Value,
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public static ItemBuilder Default()
        {
            return new ItemBuilder();
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithAddedDate(System.DateTime value)
        {
            return WithAddedDate(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithAddedDate(Func<System.DateTime> func)
        {
            _addedDate = new Lazy<System.DateTime>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutAddedDate()
        {
            _addedDate = new Lazy<System.DateTime>(default(System.DateTime));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithDescription(System.String value)
        {
            return WithDescription(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithDescription(Func<System.String> func)
        {
            _description = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutDescription()
        {
            _description = new Lazy<System.String>(default(System.String));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithExpirationDate(System.Nullable<System.DateTime> value)
        {
            return WithExpirationDate(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithExpirationDate(Func<System.Nullable<System.DateTime>> func)
        {
            _expirationDate = new Lazy<System.Nullable<System.DateTime>>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutExpirationDate()
        {
            _expirationDate = new Lazy<System.Nullable<System.DateTime>>(default(System.Nullable<System.DateTime>));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithId(System.Int32 value)
        {
            return WithId(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithId(Func<System.Int32> func)
        {
            _id = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutId()
        {
            _id = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithLocation(WhatsOnThe.Model.Location value)
        {
            return WithLocation(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithLocation(Func<WhatsOnThe.Model.Location> func)
        {
            _location = new Lazy<WhatsOnThe.Model.Location>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutLocation()
        {
            _location = new Lazy<WhatsOnThe.Model.Location>(default(WhatsOnThe.Model.Location));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithLocationId(System.Nullable<System.Int32> value)
        {
            return WithLocationId(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithLocationId(Func<System.Nullable<System.Int32>> func)
        {
            _locationId = new Lazy<System.Nullable<System.Int32>>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutLocationId()
        {
            _locationId = new Lazy<System.Nullable<System.Int32>>(default(System.Nullable<System.Int32>));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithName(System.String value)
        {
            return WithName(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithName(Func<System.String> func)
        {
            _name = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutName()
        {
            _name = new Lazy<System.String>(default(System.String));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithQuantity(System.Int32 value)
        {
            return WithQuantity(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithQuantity(Func<System.Int32> func)
        {
            _quantity = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutQuantity()
        {
            _quantity = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }

    }

    [GeneratedCode("Builders", "1.0")]
    public partial class LocationBuilder : Builder<WhatsOnThe.Model.Location>
    {
        private Lazy<System.Int32> _depth = new Lazy<System.Int32>(default(System.Int32));
        private Lazy<System.String> _description = new Lazy<System.String>(default(System.String));
        private Lazy<System.Int32> _height = new Lazy<System.Int32>(default(System.Int32));
        private Lazy<System.Int32> _id = new Lazy<System.Int32>(default(System.Int32));
        private Lazy<System.Collections.Generic.List<WhatsOnThe.Model.Item>> _items = new Lazy<System.Collections.Generic.List<WhatsOnThe.Model.Item>>(default(System.Collections.Generic.List<WhatsOnThe.Model.Item>));
        private Lazy<System.String> _name = new Lazy<System.String>(default(System.String));
        private Lazy<System.Int32> _width = new Lazy<System.Int32>(default(System.Int32));

        [GeneratedCode("ModelBuilders", "1.0")]
        public override WhatsOnThe.Model.Location Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<WhatsOnThe.Model.Location>(new WhatsOnThe.Model.Location
                {
                    Depth = _depth.Value,
                    Description = _description.Value,
                    Height = _height.Value,
                    Id = _id.Value,
                    Items = _items.Value,
                    Name = _name.Value,
                    Width = _width.Value,
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public static LocationBuilder Default()
        {
            return new LocationBuilder();
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithDepth(System.Int32 value)
        {
            return WithDepth(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithDepth(Func<System.Int32> func)
        {
            _depth = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithoutDepth()
        {
            _depth = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithDescription(System.String value)
        {
            return WithDescription(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithDescription(Func<System.String> func)
        {
            _description = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithoutDescription()
        {
            _description = new Lazy<System.String>(default(System.String));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithHeight(System.Int32 value)
        {
            return WithHeight(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithHeight(Func<System.Int32> func)
        {
            _height = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithoutHeight()
        {
            _height = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithId(System.Int32 value)
        {
            return WithId(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithId(Func<System.Int32> func)
        {
            _id = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithoutId()
        {
            _id = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithItems(System.Collections.Generic.List<WhatsOnThe.Model.Item> value)
        {
            return WithItems(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithItems(Func<System.Collections.Generic.List<WhatsOnThe.Model.Item>> func)
        {
            _items = new Lazy<System.Collections.Generic.List<WhatsOnThe.Model.Item>>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithoutItems()
        {
            _items = new Lazy<System.Collections.Generic.List<WhatsOnThe.Model.Item>>(default(System.Collections.Generic.List<WhatsOnThe.Model.Item>));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithName(System.String value)
        {
            return WithName(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithName(Func<System.String> func)
        {
            _name = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithoutName()
        {
            _name = new Lazy<System.String>(default(System.String));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithWidth(System.Int32 value)
        {
            return WithWidth(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithWidth(Func<System.Int32> func)
        {
            _width = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public LocationBuilder WithoutWidth()
        {
            _width = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }

    }

}
